name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
  push:
    branches: 
     - master

env:
  GO111MODULE: on

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The "build" workflow
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.11.x, tip]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Setup go
      run: |
        curl -sL https://raw.githubusercontent.com/maxatome/install-go/v3.0/install-go.pl |
            perl - ${{ matrix.go-version }} $HOME/go
    
    - name: Test
      run: |
        go version
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        go get -u github.com/bradleyfalzon/apicompat/cmd/apicompat
        go get -u golang.org/x/lint/golint
    - name: Run vet 
      run: go vet -x ./...

    
    - name: Lint
      run: test -z "$(golint ./...)" -e

    - name: Format code
      run: test -z "$(gofmt -s -l -w . | tee /dev/stderr)" -e
    
    - name: Run tests
      run: |
        go test -v  ./...
        go test -covermode=count -coverprofile=profile.cov
    - name: Backward compability
      run: test -z "$(apicompat -before ${{ github.event.before }} -after ${{ github.event.after}} ./... | tee /dev/stderr)" -e
      
    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov